### PR TITLE
[WIP] Groups

### PR DESCRIPTION
**Pull request by dzucconi**
group-creation

- [x] Render <CollaboratorsList /> server-side so that groups work on load.
- [x] Implement Group editing
- [x] Implement Group invites
- [x] Delete group
- [x] Search field styling
- [x] Deploy server (PR coming soon)
- [x] Ensure embeds are working
- [x] Investigate implications of `accessible_by_ids` (search, et al.)

### CODE REVIEW

**Comment by dzucconi** [comment]
group-editing

**Comment by dzucconi** [comment]
I dare say this might be done. Going to give it a good once over before merging and deploying.

**Comment by broskoski** [comment]
I've attempted to look this over and I can't really find anything to nitpick. (Apollo + React + you) really makes this implementing this stuff predictable and straightforward.

Well done, sire.

**Comment by dzucconi** [comment]
Right now things that are blocking this from production are:

- [ ] Collaborators search is bad: groups need to be prioritized over users, and user matching barely works (though this bad user matching is *currently* in prod)
- [ ] Counts not getting updated from refetch queries (only in prod)
- [ ] Feed/notifications are non-existent (only in prod)

**Comment by dzucconi** [comment]
This now covers those Q/A items and closes https://github.com/aredotna/ervell/issues/1142

I'll get this on staging and then I guess we can just deploy once it's OK'd?

**Comment by dzucconi** [comment]
searchinput

**Pull request merged**
