### PR TITLE
V/A Q/A (3)

### PR DESCRIPTION
**Pull request by dzucconi**
So: we move the contents stuff to be client-side only (which improves initial page load) and then convert the fetchPolicy to network-only; which fixes the infinite state issues.

### CODE REVIEW

**Comment by broskoski** [comment]
Sigh, there will likely be SEO implications with this.

**Comment by dzucconi** [comment]
... get on gchat

**Comment by dzucconi** [comment]
tbh i think the seo fear is unfounded but ill try to work around anyway. i do think loading the initial page faster is a better idea however.

**Comment by dzucconi** [comment]
d4ec5a53d2bf19ba640b757dea27ff5cacd97bbd is this crazy? Probably. Does it work? Yes.

Amazingly I'm still seeing the fucking Apollo parallel fetch bug.

**Comment by dzucconi** [comment]
Though seeing it *way* less. It looks like it only happens when it's also concurrent with the networkPolicy update. I'm going to leave this here for now and maybe re-approach with a deeper bugfix to the underlying issue.

**Pull request merged**
