### PR TITLE
Support dark-mode on react rendered pages (closes #1778)

### LINKED ISSUE #1778: dark mode no longer persistent on profiles
## Steps to replicate
* turn dark mode on
* go to a profile

## Expected result
Dark mode should be on

## Actual result
It is not

### PR DESCRIPTION
**Pull request by broskoski**
🌞
Quick n' dirty????

### CODE REVIEW

**Comment by dzucconi** [comment]
I hate this. Like a lot really hate it.

Add a TODO please.

**Comment by dzucconi** [comment]
TODO: support themes

**Comment by broskoski** [comment]
Ok, can also just close it if you suggest how you actually want it done.

**Comment by dzucconi** [comment]
Actually don't merge this. I've got a better idea to make this at least less horrible

**Pull request closed without merging**
