### PR TITLE
Begin on a base UI layer

### PR DESCRIPTION
**Pull request by dzucconi**
To start to work on some UI stuff I need some base components to rely on. I'm going to extract all the colors and units in an effort to improve naming as well.

Everything here is going to be isolated with the full styles on each component reset using `all initial`.

### CODE REVIEW

**Comment by dzucconi** [comment]
I will need some guidance in trimming parts of this and codifying the actual sizing and stuff. I'll include a screenshot of what this looks like state wise using the current UI.

**Comment by dzucconi** [comment]
Currently:

2017050841_1920x1408

**Comment by dzucconi** [comment]
Most puzzling to me is how h4 wound up being larger than h3

**Comment by broskoski** [comment]
🎩

**Comment by broskoski** [comment]
This looks beautiful and I have nothing critical to say about any of it.

**Comment by broskoski** [comment]
Your screenshot really does look like Helvetica though.

**Comment by dzucconi** [comment]
I'm going to merge this here. I'll ping @csherron when this is up and we'll go from there. I'm going to use some of this on https://github.com/aredotna/ervell/issues/519 so that's next.

2017051039_1920x6030

**Pull request merged**
