### PR TITLE
Tweaks embed layout

### PR DESCRIPTION
**Pull request by dzucconi**

### CODE REVIEW

**Comment by broskoski** [comment]
Should we just go ahead and pull 9 if we can? Or center that 
'+ n more blocks'?

**Comment by broskoski** [comment]
Also, looks like you aren't doing reverse position?

**Comment by dzucconi** [comment]
So: you can adjust per with a query param. It's 8 by default to favor 2-row layouts. Our super narrow blog layout is the exception not the rule.

**Comment by dzucconi** [comment]
That true.

**Pull request merged**
