### PR TITLE
Adds some analytics

### PR DESCRIPTION
**Pull request by broskoski**
Closes https://github.com/aredotna/ervell/issues/726

### CODE REVIEW

**Comment by dzucconi** [comment]
I think it's disappointing that we're mixing the analytics code in with the real code... but that's where we're at, I guess.

**Comment by broskoski** [comment]
@dzucconi what would you prefer?

**Comment by dzucconi** [comment]
TBH I have no idea; there's no great solution. Separating it out at Artsy required a bit too much busy work for my taste, and we never fully separated the two.

Mixing it together sometimes lead to bugs; and generally just interferes with refactoring.

This is fine.

**Comment by dzucconi** [comment]
I just hate analytics.

**Comment by broskoski** [comment]
I know I know, but necessary

**Pull request merged**
