### PR TITLE
Thumbnail swap

### PR DESCRIPTION
**Pull request by broskoski**
Closes https://github.com/aredotna/ervell/issues/2167
Depends on https://github.com/aredotna/api/pull/1085

@dzucconi please look when you get a chance... really feel like I could be doing something differently with all the hook stuff. Also, just FYI tried to get going with Apollo 3.0 (all the hook stuff) but had to pull it all out and move to another branch. It appears that it's going to be a bit more work to migrate.

### CODE REVIEW

**Comment by dzucconi** [comment]
Yeah I think this looks good; what's your concerns?

**Comment by broskoski** [comment]
Sorry, forgot to add a gif:

edit-thumbnail

Not really concerns, just not feeling confident that I've done the best job with the hook pattern.

**Comment by dzucconi** [comment]
Yeah your hook looks good to me, the main thing is to make sure any callbacks in it are wrapped with useCallback.

**Comment by broskoski** [comment]
@dzucconi like so? https://github.com/aredotna/ervell/pull/2179/files#diff-e785c5c4ce71532388e06701b1f53b4bR13

**Comment by dzucconi** [comment]
Yep!

**Pull request merged**
