### PR TITLE
CTA button color A/B Test

### LINKED ISSUE #1305: CTA button A/B
Apply to all logged out CTA styles

screen shot 2018-06-04 at 12 15 50 pm

https://zpl.io/bWRPxLk

### PR DESCRIPTION
**Pull request by broskoski**
Closes #1305 
screen shot 2018-06-08 at 12 33 52 pm
screen shot 2018-06-08 at 12 34 02 pm
screen shot 2018-06-08 at 12 34 08 pm

### CODE REVIEW

**Comment by dzucconi** [comment]
(We wouldn't specify the colors this way if we actually end up using this further)

**Comment by broskoski** [comment]
How would you do it?

**Comment by dzucconi** [comment]
A single color with modifiers for the states or something.

**Comment by dzucconi** [comment]
If you wanted to spec out a button of another color you wouldn't hand tool all those variations for borders, etc.

**Comment by broskoski** [comment]
Alright, if it wins, you can set it up however you please.

**Comment by dzucconi** [comment]
Sure, I mean all this stylus/jade code is dead-man-walking anyway. This is fine.

**Comment by csherron** [comment]
the button below the carousel on the homepage is still white

**Pull request merged**
